# Hue App
app:
  build: .
  ports:
    - "3000:3000"
  links:
    - cassandra
  volumes:
    - .:/usr/src/app
  command: nodemon -L index.js

# Cassandra
cassandra:
  build: cassandra/
  expose:
    - "9042"

# ML Linear Regression
ml:
  build: ml/
  links:
    - cassandra
    - rabbitmq:hulux.rabbitmq
  volumes:
    - ./ml:/usr/src/app

# RabbitMQ
rabbitmq:
  image: rabbitmq:3.6
  hostname: hulux.rabbitmq
  environment:
    - RABBITMQ_NODENAME=hulux@hulux.rabbitmq
    - RABBITMQ_ERLANG_COOKIE=hulux-cookie
    - RABBITMQ_DEFAULT_USER=hulux
    - RABBITMQ_DEFAULT_PASS=hulux
