# Hubert (Main listener)
hubert:
  build: . 
  links:
    - cassandra
    - rabbitmq:hubert
  volumes:
    - .:/usr/src/app
  command: ./bin/hubert

# Hubert Machine Learning
learn:
  build: script/
  links:
    - cassandra
    - rabbitmq:hubert.rabbitmq
  volumes:
    - ./script:/usr/src/app
  command: python index.py

# RabbitMQ
rabbitmq:
  image: rabbitmq:3.6
  hostname: hubert.rabbitmq
  environment:
    - RABBITMQ_NODENAME=hubert@hubert.rabbitmq
    - RABBITMQ_ERLANG_COOKIE=hubert-cookie
    - RABBITMQ_DEFAULT_USER=hubert
    - RABBITMQ_DEFAULT_PASS=hubert

# Cassandra
cassandra:
  build: cassandra/
  expose:
    - "9042"
